parser grammar DecaParser;

options {
    // Default language but name it anyway
    //
    language  = Java;

    // Use a superclass to implement all helper
    // methods, instance variables and overrides
    // of ANTLR default methods, such as error
    // handling.
    //
    superClass = AbstractDecaParser;

    // Use the vocabulary generated by the accompanying
    // lexer. Maven knows how to work out the relationship
    // between the lexer and parser and will build the
    // lexer before the parser. It will also rebuild the
    // parser if the lexer changes.
    //
    tokenVocab = DecaLexer;

}

// which packages should be imported?
@header {
    import fr.ensimag.deca.tree.*;
    import java.io.PrintStream;
    import fr.ensimag.deca.context.*;
}

@members {
    @Override
    protected AbstractProgram parseProgram() {
        return prog().tree;
    }
}

prog returns[AbstractProgram tree]
    : list_classes main EOF {
            assert($list_classes.tree != null);
            assert($main.tree != null);
            $tree = new Program($list_classes.tree, $main.tree);
            setLocation($tree, $list_classes.start);
        }
    ;

main returns[AbstractMain tree]
    : /* epsilon */ {
            $tree = new EmptyMain();
            setLocation($tree, $ctx.start);
        }
    | block {
            assert($block.decls != null);
            assert($block.insts != null);
            $tree = new Main($block.decls, $block.insts);
            setLocation($tree, $block.start);
        }
    ;

block returns[ListDeclVar decls, ListInst insts, Location location]
    : OBRACE list_decl list_inst CBRACE {
            assert($list_decl.tree != null);
            assert($list_inst.tree != null);
            $decls = $list_decl.tree;
            $insts = $list_inst.tree;
            $location = tokenLocation($OBRACE);
        }
    ;

list_decl returns[ListDeclVar tree]
@init   {
            $tree = new ListDeclVar();
        }
    : decl_var_set[$tree]*
    ;

decl_var_set[ListDeclVar l]
    : type list_decl_var[$l,$type.tree] SEMI
    ;

list_decl_var[ListDeclVar l, AbstractIdentifier t]
    : dv1=decl_var[$t] {
        $l.add($dv1.tree);
        } (COMMA dv2=decl_var[$t] {
            $l.add($dv2.tree);
        }
      )*
    ;

decl_var[AbstractIdentifier t] returns[AbstractDeclVar tree]
@init   {
            AbstractInitialization initialization = new NoInitialization();
        }
    : i=ident {
            assert($i.tree != null);
    
        }
      (EQUALS e=expr { 
            assert($e.tree != null);
            initialization = new Initialization($e.tree);
            setLocation(initialization, $e.start);
        }
      )? {
            assert(t != null);
            $tree = new DeclVar(t, $i.tree, initialization);
            setLocation($tree, $i.start);
        }
    ;

list_inst returns[ListInst tree]
@init {
    $tree = new ListInst();
}
    : (inst {
            $tree.add($inst.tree);
        }
      )*
    ;

inst returns[AbstractInst tree]
    : e1=expr SEMI {
            assert($e1.tree != null);
            $tree = $e1.tree;
        }
    | SEMI {
            $tree = new NoOperation();
            setLocation($tree, $SEMI);
        }
    | PRINT OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree =new Print(false,  $list_expr.tree );
            setLocation($tree, $PRINT);
        }
    | PRINTLN OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree =new Println(false,  $list_expr.tree );
            setLocation($tree, $PRINTLN);
        }
    | PRINTX OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree =new Print(true,  $list_expr.tree );
            setLocation($tree, $PRINTX);
        }
    | PRINTLNX OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree =new Println(true,  $list_expr.tree );
            setLocation($tree, $PRINTLNX);
        }
    | if_then_else {
            assert($if_then_else.tree != null);
            $tree = $if_then_else.tree;
        }
    | WHILE OPARENT condition=expr CPARENT OBRACE body=list_inst CBRACE {
            assert($condition.tree != null);
            assert($body.tree != null);
            $tree = new While($condition.tree,$body.tree);
            setLocation($tree, $WHILE);
        }
    | RETURN expr SEMI {
            assert($expr.tree != null);
            $tree = new Return($expr.tree);
            setLocation($tree, $RETURN);
        }
    ;

if_then_else returns[IfThenElse tree]
@init {
    ListInst elseBranch = new ListInst();
    class ElsifData {
        AbstractExpr cond;
        ListInst thenBranch;
        Token token;
        ElsifData(AbstractExpr c, ListInst t, Token tok) {
            cond = c; thenBranch = t; token = tok;
        }
    }
    List<ElsifData> elsifChain = new ArrayList<>();
}
    : if1=IF OPARENT condition=expr CPARENT OBRACE li_if=list_inst CBRACE {
            assert($condition.tree != null);
            assert($li_if.tree != null);
        }
      (ELSE elsif=IF OPARENT elsif_cond=expr CPARENT OBRACE elsif_li=list_inst CBRACE {
            assert($elsif_cond.tree != null);
            assert($elsif_li.tree != null);
            elsifChain.add(new ElsifData($elsif_cond.tree, $elsif_li.tree, $elsif));
        }
      )*
      (ELSE OBRACE li_else=list_inst CBRACE {
            assert($li_else.tree != null);
            elseBranch = $li_else.tree;
        }
      )?{
            for (int i = elsifChain.size() - 1; i >= 0; i--) {
                ElsifData e = elsifChain.get(i);

                ListInst wrapper = new ListInst();
                IfThenElse ite = new IfThenElse(e.cond, e.thenBranch, elseBranch);
                setLocation(ite, e.token);

                wrapper.add(ite);
                elseBranch = wrapper;
            }

            $tree = new IfThenElse($condition.tree, $li_if.tree, elseBranch);
            setLocation($tree, $if1);
      }
    ;

list_expr returns[ListExpr tree]
@init   {
            $tree = new ListExpr();
        }
    : (e1=expr {
            $tree.add($e1.tree);
        }
       (COMMA e2=expr {
            $tree.add($e2.tree);
        }
       )* )?
    ;

expr returns[AbstractExpr tree]
    : assign_expr {
            assert($assign_expr.tree != null);
            $tree = $assign_expr.tree;
        }
    ;

assign_expr returns[AbstractExpr tree]
    : e=or_expr (
        /* condition: expression e must be a "LVALUE" */ {
            assert($e.tree != null);
            if (! ($e.tree instanceof AbstractLValue) && !($e.tree instanceof AbstractReadExpr)) {
                throw new InvalidLValue(this, $ctx);
            }
            $tree = $e.tree;
        }
        EQUALS e2=assign_expr {
            assert($e.tree != null);
            assert($e2.tree != null);
            $tree = new Assign((AbstractLValue)$e.tree, $e2.tree);
            setLocation($tree, $e2.start);
        }
      | /* epsilon */ {
            assert($e.tree != null);
            $tree = $e.tree;
        }
      )
    ;

or_expr returns[AbstractExpr tree]
    : e=and_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=or_expr OR e2=and_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Or($e1.tree, $e2.tree);
            setLocation($tree, $OR);
       }
    ;

and_expr returns[AbstractExpr tree]
    : e=eq_neq_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    |  e1=and_expr AND e2=eq_neq_expr {
            assert($e1.tree != null);                         
            assert($e2.tree != null);
            $tree = new And($e1.tree, $e2.tree);
            setLocation($tree, $AND);
        }
    ;

eq_neq_expr returns[AbstractExpr tree]
    : e=inequality_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=eq_neq_expr EQEQ e2=inequality_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Equals($e1.tree, $e2.tree);
            setLocation($tree, $EQEQ);
        }
    | e1=eq_neq_expr NEQ e2=inequality_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new NotEquals($e1.tree, $e2.tree);
            setLocation($tree, $NEQ);
        }
    ;

inequality_expr returns[AbstractExpr tree]
    : e=sum_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=inequality_expr LEQ e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new LowerOrEqual($e1.tree, $e2.tree);
            setLocation($tree, $LEQ);
        }
    | e1=inequality_expr GEQ e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new GreaterOrEqual($e1.tree, $e2.tree);
            setLocation($tree, $GEQ);
        }
    | e1=inequality_expr GT e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Greater($e1.tree, $e2.tree);
            setLocation($tree, $GT);
        }
    | e1=inequality_expr LT e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Lower($e1.tree, $e2.tree);
            setLocation($tree, $LT);
        }
    | e1=inequality_expr INSTANCEOF type {
            assert($e1.tree != null);
            assert($type.tree != null);
            $tree = new InstanceOf($e1.tree , $type.tree);
            setLocation($tree, $INSTANCEOF);
        }
    ;


sum_expr returns[AbstractExpr tree]
    : e=mult_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=sum_expr PLUS e2=mult_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Plus($e1.tree, $e2.tree);
            setLocation($tree, $PLUS);
        }
    | e1=sum_expr MINUS e2=mult_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Minus($e1.tree, $e2.tree);
            setLocation($tree, $MINUS);
        }
    ;

mult_expr returns[AbstractExpr tree]
    : e=unary_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=mult_expr TIMES e2=unary_expr {
            assert($e1.tree != null);                                         
            assert($e2.tree != null);
            $tree = new Multiply($e1.tree, $e2.tree);
            setLocation($tree, $TIMES);
        }
    | e1=mult_expr SLASH e2=unary_expr {
            assert($e1.tree != null);                                         
            assert($e2.tree != null);
            $tree = new Divide($e1.tree, $e2.tree);
            setLocation($tree, $SLASH);
        }
    | e1=mult_expr PERCENT e2=unary_expr {
            assert($e1.tree != null);                                                                          
            assert($e2.tree != null);
            $tree = new Modulo($e1.tree, $e2.tree);
            setLocation($tree, $PERCENT);
        }
    ;

unary_expr returns[AbstractExpr tree]
    : op=MINUS e=unary_expr {
            assert($e.tree != null);
            $tree = new UnaryMinus($e.tree);
            setLocation($tree, $op);
        }
    | op=EXCLAM e=unary_expr {
            assert($e.tree != null);
            $tree = new Not($e.tree);
            setLocation($tree, $op);
        }
    | select_expr {
            assert($select_expr.tree != null);
            $tree = $select_expr.tree;
        }
    ;

select_expr returns[AbstractExpr tree]
    : e=primary_expr {
            assert($e.tree != null);
            $tree  = $e.tree;
        }
    | e1=select_expr DOT i=ident {
            assert($e1.tree != null);
            assert($i.tree != null);
        }
        (o=OPARENT args=list_expr CPARENT {
            // we matched "e1.i(args)"
            assert($args.tree != null);
            $tree = new MethodCall($e1.tree,$i.tree,$args.tree);
            $tree.setLocation( $e1.tree.getLocation());
        }
        | /* epsilon */ {
            // we matched "e.i"
            $tree = new Selection($e1.tree,$i.tree);
            $tree.setLocation( $e1.tree.getLocation());
        }
        )
    ;

primary_expr returns[AbstractExpr tree]
    : ident {
            assert($ident.tree != null);
            $tree = $ident.tree;
        }
    | m=ident OPARENT args=list_expr CPARENT {
            assert($args.tree != null);
            assert($m.tree != null);
            This thistemp = new This(true);
            thistemp.setLocation($m.tree.getLocation());
            $tree = new MethodCall(thistemp,$m.tree,$args.tree);
            $tree.setLocation($m.tree.getLocation());
        }
    | OPARENT expr CPARENT {
            assert($expr.tree != null);
            $tree = $expr.tree;
        }
    | READINT OPARENT CPARENT {
            $tree = new ReadInt();
            setLocation($tree, $READINT);
        }
    | READFLOAT OPARENT CPARENT {
            $tree = new ReadFloat();
            setLocation($tree, $READFLOAT);
        }
    | NEW ident OPARENT CPARENT {
            assert($ident.tree != null);
            $tree = new New($ident.tree);
            setLocation($tree, $NEW);
        }
    | cast=OPARENT type CPARENT OPARENT expr CPARENT {
            assert($type.tree != null);
            assert($expr.tree != null);
            $tree = new Cast($type.tree, $expr.tree);
            setLocation($tree, $cast);
        }
    | literal {
            assert($literal.tree != null);
            $tree = $literal.tree;
        }
    ;

type returns[AbstractIdentifier tree]
    : ident {
            assert($ident.tree != null);
            $tree = $ident.tree;
        }
    ;

literal returns[AbstractExpr tree]
    : INT {
            $tree =new IntLiteral(Integer.parseInt($INT.text));
            setLocation($tree, $INT);
        }
    | fd=FLOAT {
            Float temp = Float.parseFloat($fd.text);
            if(Float.isInfinite(temp) || Float.isNaN(temp)){
                throw new InvalidFloat(this, $ctx);
            }
            $tree =new FloatLiteral(temp);
            setLocation($tree, $fd);
        }
    | s=multi_line_string {
        $tree =new StringLiteral($s.text);
        $tree.setLocation($s.location);
        }
    | TRUE {
        $tree = new BooleanLiteral(true);
        setLocation($tree, $TRUE);
    }
    | FALSE {
        $tree = new BooleanLiteral(false);
        setLocation($tree, $FALSE);
    }
    | THIS {
        $tree = new This(false);
        setLocation($tree, $THIS);
    }
    | NULL {
        $tree = new nullLiteral();
        setLocation($tree, $NULL);
    }
    ;

ident returns[AbstractIdentifier tree]
    : IDENT {
            $tree = new Identifier(getDecacCompiler().symbolTable.create($IDENT.text));
            setLocation($tree, $IDENT);
        }
    ;

/****     Class related rules     ****/

list_classes returns[ListDeclClass tree]
@init {
    $tree = new ListDeclClass();
}    :
      (c1=class_decl {
            $tree.add($c1.tree);

        }
      )*
    ;

class_decl returns[DeclClass tree]
    : CLASS name=ident superclass=class_extension 
    OBRACE class_body CBRACE {
            $tree = new DeclClass($name.tree, $superclass.tree, 
                                  $class_body.fields, $class_body.methods);
            setLocation($tree, $CLASS);
    }
    ;


class_extension returns[AbstractIdentifier tree]
    : EXTENDS ident {
        $tree = $ident.tree;
    }
    | /* epsilon */ {
            $tree = new Identifier(getDecacCompiler().symbolTable.create("Object"));
            setLocation($tree, $ctx.start);
        }
    ;


class_body returns[ListDeclField fields, ListDeclMethod methods]
@init {
    $fields = new ListDeclField();
    $methods = new ListDeclMethod();
}
    : (m=decl_method {
            assert($m.tree != null);
            $methods.add($m.tree);
        }
      | fs=decl_field_set {
            for(AbstractDeclField field : $fs.fields) {
                assert(field != null);
                $fields.add(field);
            }
        }
      )*
    ;


decl_field_set returns[List<AbstractDeclField> fields]
@init {
    $fields = new ArrayList<>();
}
    : v=visibility ty=type ldf=list_decl_field[$v.vis, $ty.tree]
      SEMI {
            if($ldf.fields.isEmpty()){ 
                throw new InvalideField(this,$ctx);
            }
            $fields = $ldf.fields;
        }
    ;


visibility returns[Visibility vis]
    : /* epsilon */ {
        $vis = Visibility.PUBLIC;
    }
    | PROTECTED {
        $vis = Visibility.PROTECTED;
        }
    ;



list_decl_field[Visibility vis, AbstractIdentifier Type] 
    returns[List<AbstractDeclField> fields]
@init {
    $fields = new ArrayList<AbstractDeclField>();
}
    : dv1=decl_field[$vis, $Type] {
        assert($dv1.tree != null);
        $fields.add($dv1.tree);
      }
      (COMMA dv2=decl_field[$vis, $Type] {
        assert($dv2.tree != null);
        $fields.add($dv2.tree);
      })*
    ;


decl_field[Visibility vis, AbstractIdentifier Type] 
    returns[AbstractDeclField tree]
@init {
    AbstractInitialization init = new NoInitialization();
}
    : i=ident {
        assert($i.tree != null);
      }
      (EQUALS e=expr {
        assert($e.tree != null);
        init = new Initialization($e.tree);
        setLocation(init, $e.start);
      })? {
        $tree = new DeclField($vis, $Type, $i.tree , init);
        setLocation($tree, $i.start);
      }
    ;


decl_method returns[AbstractDeclMethod tree]
@init {
    $tree = null;
    AbstractMethodBody body =null;
}
    : type ident OPARENT params=list_params CPARENT (block {
            body = new MethodBody( $block.decls, $block.insts);
            body.setLocation($block.location);
        }
      | ASM OPARENT code=multi_line_string CPARENT SEMI {
            body = new MethodAsmBody(new StringLiteral($code.text));
            setLocation(body, $ASM);
        }
      ) {
        assert($params.tree != null);
        assert($type.tree != null);
        assert($ident.tree != null);
        $tree = new DeclMethod( $type.tree, $ident.tree, $params.tree, body);
        $tree.setLocation($type.tree.getLocation());
    }
    ;

list_params returns[ListDeclParam tree]
@init {
    $tree = new ListDeclParam();
}
    : (p1=param {
            assert($p1.tree != null);
            $tree.add($p1.tree);
        } (COMMA p2=param {
            assert($p2.tree != null);
            $tree.add($p2.tree);
        }
      )*)?
    ;
    
multi_line_string returns[String text, Location location]
    : s=STRING {
            $text = $s.text;
            $location = tokenLocation($s);
        }
    | s=MULTI_LINE_STRING {
            $text = $s.text;
            $location = tokenLocation($s);
        }
    ;

param returns[DeclParam tree]
    : type ident {
            assert($type.tree != null);
            assert($ident.tree != null);
            $tree = new DeclParam( $type.tree,  $ident.tree);
            $tree.setLocation($ident.tree.getLocation());
        }
    ;